development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: certificate_rails
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: certificate_rails
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username:
  password:
